name: Update README

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/576328904266/locations/global/workloadIdentityPools/github/providers/cheahjs-org"
          project_id: ${{ secrets.GCP_PROJECT }}
      - name: Run script
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
          HYPERBOLIC_API_KEY: ${{ secrets.HYPERBOLIC_API_KEY }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
          LAMBDA_API_KEY: ${{ secrets.LAMBDA_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          SCALEWAY_API_KEY: ${{ secrets.SCALEWAY_API_KEY }}
        run: |
          python -u src/pull_available_models.py
      - name: Remove credentials
        run: |
          rm ${{ steps.auth.outputs.credentials_file_path }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Update README with latest models"
          body: "This PR updates the README with the latest available models."
          branch: update-readme-${{ github.run_id }}
          base: main
          commit-message: "Update README with latest models"
